### ISSUE TITLE
项目运行起来后在微信开发者工具中报错

### ISSUE THREAD

**Issue by coderlaoma** [T-Mach/wepy-classic-template#1]
您好，请教一下，我装了最新的2.0.x版本wepy，下载项目跑起来后，在微信开发者工具中报错，如下图所示
![image](https://user-images.githubusercontent.com/8630511/66177332-a9829880-e693-11e9-8838-3631f7ec0266.png)

**Comment by s6nqou** [comment]
要用最新的@wepy/cli和@wepy/core才行，但是还没release，所以要手动的替换这两个包
* @wepy/cli: https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/Tencent/wepy/tree/2.0.x/packages/cli
* @wepy/core: https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/Tencent/wepy/tree/2.0.x/packages/core

下载之后解压到 `node_modules/@wepy` 下面，然后重新编译就行了，有问题可以再问我

**Comment by coderlaoma** [comment]
@T-Mach 可以了，谢谢
